import React from "react";
import rectangle4 from "./rectangle-4.svg";
import union from "./union.svg";
import vector1 from "./vector-1.svg";

// Generated by AI

export const Desktop = () => {
  return (
    <div className="bg-white w-full min-w-[1440px] min-h-[1024px] relative">
      <div className="absolute top-12 left-0 w-[1440px] h-[976px] bg-[#060639]" />

      <div className="absolute top-12 left-[calc(50.00%_-_418px)] w-[836px] h-[976px] bg-[#ffd387]">
        <img
          className="absolute top-0 left-[calc(50.00%_-_410px)] w-[820px] h-[976px]"
          alt="Rectangle"
          src={rectangle4}
        />

        <div className="absolute top-[856px] left-0 w-[836px] h-[120px] bg-[linear-gradient(180deg,rgba(255,255,255,0)_0%,rgba(220,220,220,1)_100%)]" />
      </div>

      <button className="all-[unset] box-border absolute top-[888px] left-[calc(50.00%_-_167px)] w-[333px] h-[72px]">
        <div className="absolute -top-px left-[calc(50.00%_-_168px)] w-[335px] h-[74px] bg-[#fff2e1] rounded-lg border border-solid border-[#9c6721]" />

        <div className="absolute top-[calc(50.00%_-_20px)] left-[calc(50.00%_-_138px)] w-[279px] h-10">
          <div className="absolute top-[calc(50.00%_-_20px)] left-[calc(50.00%_-_140px)] [font-family:'Young_Serif-Regular',Helvetica] font-normal text-black text-[28px] tracking-[0] leading-[normal]">
            Upload Document
          </div>

          <img
            className="absolute top-[calc(50.00%_-_13px)] left-[261px] w-[18px] h-[25px]"
            alt="Vector"
            src={vector1}
          />
        </div>
      </button>

      <div className="absolute w-[724px] h-[632px] top-24 left-[358px] flex flex-col">
        <div className="w-[728px] h-[184px] flex flex-col gap-1.5">
          <div className="w-[212px] h-[34px] [font-family:'Young_Serif-Regular',Helvetica] font-normal text-black text-2xl tracking-[0] leading-[normal] underline">
            First Amendment
          </div>

          <p className="w-[724px] h-36 [font-family:'Albert_Sans-Regular',Helvetica] font-normal text-black text-xl tracking-[0] leading-[normal]">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat. Duis aute irure dolor in
            reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
            pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
            culpa qui officia deserunt mollit anim id est laborum.
          </p>
        </div>

        <div className="w-[728px] h-[184px] mt-4 flex flex-col gap-1.5">
          <div className="w-[239px] h-[34px] [font-family:'Young_Serif-Regular',Helvetica] font-normal text-black text-2xl tracking-[0] leading-[normal] underline">
            Second Amendment
          </div>

          <p className="w-[724px] h-36 [font-family:'Albert_Sans-Regular',Helvetica] font-normal text-black text-xl tracking-[0] leading-[normal]">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat. Duis aute irure dolor in
            reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
            pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
            culpa qui officia deserunt mollit anim id est laborum.
          </p>
        </div>

        <div className="w-[728px] h-[184px] mt-4 flex flex-col gap-1.5">
          <div className="w-[225px] h-[34px] [font-family:'Young_Serif-Regular',Helvetica] font-normal text-black text-2xl tracking-[0] leading-[normal] underline">
            Third Amendment
          </div>

          <p className="w-[724px] h-36 [font-family:'Albert_Sans-Regular',Helvetica] font-normal text-black text-xl tracking-[0] leading-[normal]">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat. Duis aute irure dolor in
            reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
            pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
            culpa qui officia deserunt mollit anim id est laborum.
          </p>
        </div>

        <div className="w-16 mt-8 flex gap-2">
          <div className="w-4 h-4 rounded-lg border-2 border-solid border-black" />

          <div className="w-4 h-4 rounded-lg border-2 border-solid border-black" />

          <div className="w-4 h-4 rounded-lg border-2 border-solid border-black" />
        </div>
      </div>

      <div className="absolute top-0 left-0 w-[1440px] h-12 flex justify-center bg-black">
        <div className="mt-[5.8px] w-[725px] h-[37.21px] ml-[-651.0px] relative">
          <div className="absolute top-[3px] left-[calc(50.00%_+_293px)] [font-family:'Young_Serif-Regular',Helvetica] font-normal text-white text-2xl tracking-[0] leading-[normal]">
            Menu
          </div>

          <div className="absolute top-0 left-0 w-[141px] h-[37px]">
            <div className="absolute top-[3px] left-[29px] [font-family:'Young_Serif-Regular',Helvetica] font-normal text-white text-2xl tracking-[0] leading-[normal]">
              egisLight
            </div>

            <img
              className="absolute w-[35px] h-9 top-0 left-0"
              alt="Union"
              src={union}
            />
          </div>
        </div>
      </div>
    </div>
  );
};
